# Generated by Django 3.2.16 on 2025-02-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': '博客信息', 'verbose_name_plural': '博客信息'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论信息', 'verbose_name_plural': '评论信息'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签信息', 'verbose_name_plural': '标签信息'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
